# This overlay is a HACK to prevent someone from accidentally commiting DEV changes in the base manifests
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../authentication
images:
  # Since kustomize will transform the image in the base resource(s), we need to search from that post-transform name
  #   Each "name" property should match the image "newName" defined in the base resource(s)
- name: quay.io/opendatahub/odh-dashboard
  newName: <DEV_DASHBOARD_QUAY_URL>
  newTag: <DEV_DASHBOARD_QUAY_TAG>
- name: registry.redhat.io/openshift4/ose-oauth-proxy
  newName: registry.redhat.io/openshift4/ose-oauth-proxy
  newTag: v4.8
