kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
      - config.openshift.io
    resources:
      - clusterversions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - subscriptions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - configmaps
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consolelinks
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operator.openshift.io
    resources:
      - consoles
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
      - integreatly.org
    resources:
      - rhmis
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - user.openshift.io
    resources:
      - groups
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - serviceaccounts
      - secrets
      - services
      - namespaces
  - verbs:
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
