apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
namespace: odh-dashboard
resources:
- role.yaml
- cluster-role.yaml
- service-account.yaml
- role-binding.yaml
- cluster-role-binding.yaml
- deployment.yaml
- routes.yaml
- service.yaml
images:
- name: odh-dashboard
  newName: quay.io/opendatahub/odh-dashboard
  newTag: v1.0
