apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../core-bases/base
- federation-configmap.yaml
- networkpolicy.yaml
configMapGenerator:
- envs:
  - params.env
  name: modular-architecture-params
generatorOptions:
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.model-registry-ui-image
  name: model-registry-ui-image
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: modular-architecture-params
- fieldref:
    fieldPath: data.gen-ai-ui-image
  name: gen-ai-ui-image
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: modular-architecture-params
configurations:
- params.yaml
patches:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: dashboard
    version: v1
- path: service.yaml
  target:
    kind: Service
    name: dashboard
    version: v1
