kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-hardware-profiles-permissions
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
rules:
  - apiGroups:
      - dashboard.opendatahub.io
    verbs:
      - get
      - list
      - watch
    resources:
      - hardwareprofiles
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-accelerator-profiles-permissions
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
rules:
  - apiGroups:
      - dashboard.opendatahub.io
    verbs:
      - get
      - list
      - watch
    resources:
      - acceleratorprofiles
