apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
- rhoam-app.yaml
- deploy-model-rhoam-quickstart.yaml
