name: "workspaces/controller: unit-tests"

permissions: {}

on:
  push:
    branches: [ "main", "notebooks-v2", "v*-branch" ]
  pull_request:
    paths: [ "workspaces/controller/**" ]
    branches: [ "main", "notebooks-v2", "v*-branch" ]

jobs:

  "unit-tests":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: workspaces/controller/go.mod
          check-latest: true
          cache-dependency-path: workspaces/controller/go.sum

      - name: Test
        run: make test
        working-directory: workspaces/controller
