- op: replace
  path: /metadata/name
  value: rhods-dashboard
- op: replace
  path: /spec/replicas
  value: 5
- op: replace
  path: /spec/selector/matchLabels/deployment
  value: rhods-dashboard
- op: replace
  path: /spec/template/metadata/labels/deployment
  value: rhods-dashboard
- op: replace
  path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchExpressions/0/values/0
  value: rhods-dashboard
- op: replace
  path: /spec/template/spec/containers/0/name
  value: rhods-dashboard
- op: replace
  path: /spec/template/spec/containers/0/image
  value: $(odh-dashboard-image)
- op: replace
  path: /spec/template/spec/serviceAccount
  value: rhods-dashboard
- op: replace
  path: /spec/template/spec/imagePullSecrets
  value:
    - name: addon-managed-odh-pullsecret