apiVersion: kubeflow.org/v1beta1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace-controller
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  # TODO(user): Add fields here
