kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: kserve-ovms
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/ootb: 'true'
  annotations:
    tags: 'kserve-ovms,servingruntime'
    description: 'OpenVino Model Serving Definition'
    opendatahub.io/modelServingSupport: '["single"]'
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  labels:
    opendatahub.io/dashboard: 'true'
  metadata:
    annotations:
      openshift.io/display-name: OpenVINO Model Server
      opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    name: kserve-ovms
  spec:
    multiModel: false
    annotations:
      prometheus.kserve.io/port: '8888'
      prometheus.kserve.io/path: /metrics
    supportedModelFormats:
    - name: openvino_ir
      version: opset11
      autoSelect: true
    - name: onnx
      version: '1'
    - name: tensorflow
      version: '1'
      autoSelect: true
    - name: tensorflow
      version: '2'
      autoSelect: true
    - name: paddle
      version: '2'
      autoSelect: true
    protocolVersions:
    - v2
    - grpc-v2
    containers:
    - name: kserve-container
      image: 'ovms-kserve'
      args:
      - '--model_name={{.Name}}'
      - '--port=8001'
      - '--rest_port=8888'
      - '--model_path=/mnt/models'
      - '--file_system_poll_wait_seconds=0'
      - '--grpc_bind_address=127.0.0.1'
      - '--rest_bind_address=127.0.0.1'
      ports:
      - containerPort: 8888
        protocol: TCP