apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agentic-starter-kits-app.yaml
  - agentic-starter-kits-langgraph-tutorial.yaml
  - agentic-starter-kits-llamaindex-tutorial.yaml
  - agentic-starter-kits-llamastack-tutorial.yaml
  - agentic-starter-kits-rag-tutorial.yaml
