kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard # {"$openapi":"DASHBOARD_NAME"}
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kfdef.apps.kubeflow.org
  resources:
  - kfdefs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
  resources:
  - configmaps
  - secrets
- apiGroups:
  - batch
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
  resources:
  - cronjobs
  - jobs
- apiGroups:
  - image.openshift.io
  verbs:
  - create
  - get
  - patch
  resources:
  - imagestreams
- apiGroups:
  - applications.console.openshift.io
  resources:
  - odhapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - applications.console.openshift.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - applications.console.openshift.io
  resources:
  - odhapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - documents.console.openshift.io
  resources:
  - odhdocuments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - documents.console.openshift.io
  resources:
  - odhdocuments/finalizers
  verbs:
  - update
- apiGroups:
  - documents.console.openshift.io
  resources:
  - odhdocuments/status
  verbs:
  - get
  - patch
  - update
