apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: controller-manager

images:
- name: workspaces-controller
  newName: ghcr.io/kubeflow/notebooks/workspaces-controller
  newTag: latest
