apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow-workspaces

resources:
- namespace.yaml
- service_account.yaml
- rbac.yaml
- service.yaml
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: api

images:
- name: workspaces-backend
  newName: ghcr.io/kubeflow/notebooks/workspaces-backend
  newTag: latest
