apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../modular-architecture
patches:
- path: role-binding.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: dashboard
    version: v1
- path: cluster-role-binding.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: dashboard
    version: v1
- path: auth-delegator.clusterrolebinding.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: dashboard-auth-delegator
    version: v1
- path: cluster-monitoring-role-binding.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: dashboard-monitoring
    version: v1
- path: federation-configmap.yaml
