apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - ../common
  - ../modular-architecture
  - ../core-bases/consolelink
  - ./apps
configMapGenerator:
  - name: odh-dashboard-params
    env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: odh-dashboard-image
    objref:
      kind: ConfigMap
      name: odh-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-dashboard-image
  - name: kube-rbac-proxy
    objref:
      kind: ConfigMap
      name: odh-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.kube-rbac-proxy
  - name: section-title
    objref:
      kind: ConfigMap
      name: odh-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.section-title
  - name: dashboard-url
    objref:
      kind: ConfigMap
      name: odh-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.dashboard-url
  - name: gateway-name
    objref:
      kind: ConfigMap
      name: odh-dashboard-params
      apiVersion: v1
    fieldref:
      fieldpath: data.gateway-name
configurations:
  - params.yaml
replacements:
  - source:
      kind: ConfigMap
      name: odh-dashboard-params
      fieldPath: data.gateway-domain
    targets:
      - select:
          kind: Deployment
          name: odh-dashboard
        fieldPaths:
          - spec.template.spec.containers.[name=odh-dashboard].env.[name=GATEWAY_DOMAIN].value
          - spec.template.spec.containers.[name=gen-ai-ui].env.[name=GATEWAY_DOMAIN].value
          - spec.template.spec.containers.[name=model-registry-ui].env.[name=GATEWAY_DOMAIN].value
          - spec.template.spec.containers.[name=maas-ui].env.[name=GATEWAY_DOMAIN].value
