apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common
- ../modular-architecture
- ../core-bases/consolelink
configMapGenerator:
- envs:
  - params.env
  name: odh-dashboard-params
generatorOptions:
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.odh-dashboard-image
  name: odh-dashboard-image
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: odh-dashboard-params
- fieldref:
    fieldPath: data.kube-rbac-proxy
  name: kube-rbac-proxy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: odh-dashboard-params
- fieldref:
    fieldPath: data.section-title
  name: section-title
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: odh-dashboard-params
- fieldref:
    fieldPath: data.dashboard-url
  name: dashboard-url
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: odh-dashboard-params
- fieldref:
    fieldPath: data.gateway-name
  name: gateway-name
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: odh-dashboard-params
configurations:
- params.yaml
labels:
- includeSelectors: true
  pairs:
    app: dashboard
    app.kubernetes.io/part-of: dashboard
