apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dashboard-perses-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: perses-operator
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: redhat-ods-applications
          podSelector:
            matchLabels:
              app.kubernetes.io/part-of: rhods-dashboard
      ports:
        - protocol: TCP
          port: 8080
